Creating an eks cluster
dokc/continuous-kubernetes pull request #3
Opened 2020-09-02 20:05 UTC by prabhatkumarthakur

This commit adds github actions file which performs the following:

1. Install eksctl
2. Configure AWS credentials from secrets
3. Create EKS cluster using eksctl
4. Install OpenEBS
5. Install csi driver

2020-09-03 06:47 UTC, AmitKumarDas commented on eks/volumeattachment_add.sh
> +    sed  "s/nodeName:.*$/nodeName: ${nodes[i]}/g" -i ./eks/volumeattachment.yaml
- Create new volume attachment yamls from `volumeattachment.yaml.tpl`
- Name them as volumeattachment-<nodename>-<pvname>.yaml
- Place these files at `/tmp/delete/`
- Later run `kubectl delete -f /tmp/delete/` during cleanup

2020-09-03 06:47 UTC, AmitKumarDas commented on eks/volumeattachment.yaml
> +    finalizers:
remove finalizers
remove annotations
remove status
remove kind: List

2020-09-03 06:48 UTC, AmitKumarDas commented on eks/suite.sh
> +echo -e "/n++++++++++++++++++++++++++++++++++"
Put cleanup in a TRAP function

2020-09-03 13:34 UTC, AmitKumarDas commented on eks/suite.sh
> +eksctl create cluster -f ./eks/cluster.yaml
make use of the direct yaml i.e. `./cluster.yaml`

2020-09-03 13:34 UTC, AmitKumarDas commented on eks/suite.sh
> +kubectl apply -f ./eks/storageclass.yaml
same comment

2020-09-03 13:34 UTC, AmitKumarDas commented on eks/suite.sh
> +kubectl apply -f ./eks/pvc1.yaml -f ./eks/pvc2.yaml -f ./eks/pvc3.yaml
same comment

2020-09-03 13:34 UTC, AmitKumarDas commented on .github/workflows/action.yml
> +name: Github action to create EKS cluster using eksctl
The final PR needs to have a single commit

2020-09-08 05:47 UTC, AmitKumarDas commented on eks/volumeattachment_add.sh
> +    sed  "s/nodeName:.*$/nodeName: ${nodes[i]}/g" -i ./eks/volumeattachment_template.yaml
- Don't modify the _template.yaml
- volumeattachment.sh:
mkdir -p .tmp/volumeattachment
for {
cp _template.yaml .tmp/volumeattachment/nodename-volumename.yaml
run sed commands .tmp/volumeattachment/nodename-volumename.yaml
}
- delete.sh:
kubectl delete -f .tmp/volumeattachment/

2020-09-08 05:48 UTC, AmitKumarDas commented on eks/volumeattachment_template.yaml
> +apiVersion: storage.k8s.io/v1
Explain in comments

2020-09-08 05:48 UTC, AmitKumarDas commented on eks/volumeattachment_template.yaml
> +  name:
Explain in comments who is going to set the name

2020-09-08 05:48 UTC, AmitKumarDas commented on eks/volumeattachment_template.yaml
> +  nodeName:
Explain in comments who is going to set the nodename

2020-09-08 05:49 UTC, AmitKumarDas commented on eks/volumeattachment_template.yaml
> +    persistentVolumeName:
Explain in comments who is going to set the persistentVolumeName

2020-09-08 11:52 UTC, amitbhatt818 requested changes

2020-09-08 11:52 UTC, amitbhatt818 commented on eks/cleanup.sh
> +    kubectl delete -f https://openebs.github.io/charts/openebs-operator.yaml
can you please create two separate files one for deleting openebs and its dependencies and the other to delete eksctl cluster

2020-09-08 11:52 UTC, amitbhatt818 commented on eks/suite.sh
> +echo -e "\nInstall Amazon EBS CSI driver"
create one seperate file which should have these all tasks:
 install ebs csi , install storage class,create disk,Install volumeattachment,etc

2020-09-09 09:58 UTC, harshshekhar15 reviewed
@prabhatkumarthakur let's try to put in checks instead of manual sleeps to check if something is running fine or not.

2020-09-09 09:58 UTC, harshshekhar15 commented on eks/suite.sh
> +kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"
Deploy a specific version instead of deploying from master.

2020-09-09 09:58 UTC, harshshekhar15 commented on eks/suite.sh
> +kubectl get pod -n kube-system
Put a check to see if everything is running fine in `kube-system` before deploying anything.

2020-09-09 09:58 UTC, harshshekhar15 commented on eks/suite.sh
> +kubectl get po -n openebs
Put a check to see if all the openebs components are running fine, instead of manual sleep.

2020-09-09 10:06 UTC, prabhatkumarthakur commented on eks/suite.sh
> +kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"
This will always deploy the latest stable csi driver version eg (0.6.0) for now

2020-09-10 06:01 UTC, prabhatkumarthakur commented on eks/cleanup.sh
> +    kubectl delete -f https://openebs.github.io/charts/openebs-operator.yaml
Addressed the review comment

2020-09-10 06:02 UTC, prabhatkumarthakur commented on eks/suite.sh
> +echo -e "\nInstall Amazon EBS CSI driver"
Addressed the review comments

2020-09-10 06:03 UTC, prabhatkumarthakur commented on eks/volumeattachment_template.yaml
> +apiVersion: storage.k8s.io/v1
done

2020-09-10 17:35 UTC, harshshekhar15 commented on eks/suite.sh
> +kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"
Correct but IMO we should stick to the latest stable version instead of master as any breaking changes in future might break the entire flow.

2020-09-11 16:09 UTC, prabhatkumarthakur commented on eks/suite.sh
> +kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"
I am using the command given in AWS ebs csi driver installation doc.
https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html
https://github.com/kubernetes-sigs/aws-ebs-csi-driver

2020-09-14 06:20 UTC, AmitKumarDas commented on experiments/assert-kubesystem-pod.yaml
> +  - name: assert-running-of-ebs-csi-node
`assert-running-of-ebs-csi-node` to `assert-if-ebs-csi-node-is-running`

2020-09-14 06:59 UTC, prabhatkumarthakur commented on .github/workflows/action.yml
> +name: Github action to create EKS cluster using eksctl
done

2020-09-14 08:13 UTC, AmitKumarDas approved these changes

2020-09-14 08:14 UTC, merged