feat(add): readme for cassandra installation using kudo
dokc/continuous-kubernetes pull request #8
Opened 2020-09-29 12:53 UTC by prabhatkumarthakur

- In this PR I have added a readme that describes the use case, Cassandra deployment using Kudo with openebs device storage class.
- Modified the folder structure

## Folder structure
```
ontinuous-kubernetes
├── eks
│   ├── cassandra-deploy
│   │   ├── assert-cassandra-pod.yaml
│   │   ├── cassandra-inference.yaml
│   │   ├── cassandra_install.sh
│   │   ├── cassandra_uninstall.sh
│   │   └── README.md
│   ├── eks-setup
│   │   ├── cluster.yaml
│   │   ├── eks_install.sh
│   │   └── eks_uninstall.sh
│   ├── experiments
│   │   ├── assert-cert-manger-pod.yaml
│   │   ├── assert-kubesystem-pod.yaml
│   │   ├── assert-openebs-pod.yaml
│   │   ├── cert-manager-inference.yaml
│   │   ├── ci.yml
│   │   └── inference.yaml
│   ├── kudo-operator
│   │   ├── kudo_install.sh
│   │   └── kudo_uninstall.sh
│   └── openebs
│       ├── disk.yaml
│       ├── openebs_install.sh
│       ├── openebs_uninstall.sh
│       ├── storageclass.yaml
│       ├── volumeattachment.sh
│       └── volumeattachment_template.yaml
├── LICENSE
├── Makefile
└── README.md
```

2020-10-01 05:26 UTC, ranjithwingrider commented on .github/workflows/action.yml
> +name: Github action to create EKS cluster and deploy cassandra sts
cassandra sts ->  Cassandra StatefulSet

2020-10-01 05:31 UTC, ranjithwingrider commented on eks/cassandra-deploy/README.md
> +In this usecase below activity have been performed:
In this usecase below activity have been performed:- > 
In this use case , the following steps are performed

2020-10-01 05:31 UTC, ranjithwingrider commented on eks/cassandra-deploy/README.md
> +- Create a 3 node EKS cluster in ap-south-1 region
ap-south-1 -> `ap-south-1`

2020-10-01 05:36 UTC, ranjithwingrider commented on eks/cassandra-deploy/README.md
> +- Create an Amazon csi volume and use the same as a block devices attached to each node
Create an Amazon csi volume and use the same as a block devices attached to each node -> 
Create an Amazon EBS volume and attach it to each node.

2020-10-01 05:36 UTC, ranjithwingrider commented on eks/cassandra-deploy/README.md
> +- Deploy Cassandra statefulset using kudo operator and openebs-device as storage class
openebs-device -> `openebs-device`

2020-10-01 05:37 UTC, ranjithwingrider commented on eks/cassandra-deploy/README.md
> +- Deploy Cassandra statefulset using kudo operator and openebs-device as storage class
storage class -> `Storage Class`

2020-10-01 05:37 UTC, ranjithwingrider commented on eks/cassandra-deploy/README.md
> +- Check the status of cassandra sts pods.
cassandra sts -> Cassandra

2020-10-01 06:04 UTC, gprasath requested changes

2020-10-01 06:04 UTC, gprasath commented on eks/cassandra-deploy/README.md
> +- Create an Amazon csi volume and use the same as a block devices attached to each node
Is the number of volumes based on number of nodes?

2020-10-01 06:04 UTC, gprasath commented on eks/cassandra-deploy/README.md
> +- Deploy cert-manager
Is cert-manager , a prerequisite for kudo-operator deployment?

2020-10-01 06:04 UTC, gprasath commented on eks/cassandra-deploy/README.md
> +- Delete the disks
aren't we deleting pvc?

2020-10-01 06:04 UTC, gprasath commented on eks/cassandra-deploy/cassandra_install.sh
> +sleep 35
how many replicas this sts has? It should be configurable

2020-10-01 06:04 UTC, gprasath commented on eks/cassandra-deploy/cassandra_install.sh
> +sleep 35
why do we sleep? Instead we need to check if the kudo-operator has started running

2020-10-06 07:22 UTC, prabhatkumarthakur commented on .github/workflows/action.yml
> +name: Github action to create EKS cluster and deploy cassandra sts
done

2020-10-06 07:22 UTC, prabhatkumarthakur commented on eks/cassandra-deploy/README.md
> +In this usecase below activity have been performed:
done

2020-10-06 07:26 UTC, prabhatkumarthakur commented on eks/cassandra-deploy/README.md
> +- Create a 3 node EKS cluster in ap-south-1 region
@gprasath yes,we can make changes in the cluster.yaml to deploy the cluster in other regions.

2020-10-06 07:29 UTC, prabhatkumarthakur commented on eks/cassandra-deploy/README.md
> +- Create an Amazon csi volume and use the same as a block devices attached to each node
yes, the script had been written to create 3 volumes for 3 nodes.
@gprasath  I have followed the below doc and automated the same. The aim was to run everything from a laptop or Github action without any manual intervention.
https://mayadata.io/workloads/cassandra-on-kubernetes

2020-10-06 07:30 UTC, prabhatkumarthakur commented on eks/cassandra-deploy/README.md
> +- Deploy Cassandra statefulset using kudo operator and openebs-device as storage class
done

2020-10-06 07:30 UTC, prabhatkumarthakur commented on eks/cassandra-deploy/README.md
> +- Deploy Cassandra statefulset using kudo operator and openebs-device as storage class
done

2020-10-06 07:30 UTC, prabhatkumarthakur commented on eks/cassandra-deploy/README.md
> +- Check the status of cassandra sts pods.
done

2020-10-06 07:45 UTC, prabhatkumarthakur commented on Makefile
> +	@cd eks/kudo-operator && ./kudo_install.sh
I will move kudo-operator outside eks folder

2020-10-06 07:51 UTC, prabhatkumarthakur commented on eks/cassandra-deploy/README.md
> +- Deploy cert-manager
yes, As per the workload article it is required.

2020-10-06 07:55 UTC, prabhatkumarthakur commented on eks/cassandra-deploy/README.md
> +- Delete the disks
yes, we are deleting it in openebs uninstallation step.

2020-10-06 07:57 UTC, prabhatkumarthakur commented on eks/cassandra-deploy/cassandra_install.sh
> +sleep 35
The default replica count for Cassandra is 3.
We are checking the kudo-operator running status in kundo_install.sh script.

2020-10-06 09:24 UTC, ranjithwingrider commented on eks/cassandra-deploy/README.md
> +- Deploy Cassandra statefulset using kudo operator and openebs-device as storage class
Try to use the same word everywhere for Storage Class instead of storage class.
Also change kudo to Kudo

2020-10-06 09:25 UTC, ranjithwingrider commented on eks/cassandra-deploy/README.md
> +- Deploy Cassandra statefulset using kudo operator and openebs-device as storage class
Use Kudo instead of kudo everywhere.

2020-10-06 09:26 UTC, ranjithwingrider commented on eks/cassandra-deploy/README.md
> +- Check the status of cassandra sts pods.
cassandra  -> Cassandra

2020-10-06 10:25 UTC, ranjithwingrider approved these changes
Looks good with the content.

2020-10-07 07:42 UTC, gprasath approved these changes

2020-10-07 09:46 UTC, merged